# Generated by Django 5.2.1 on 2026-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstprojectt', '0002_alter_task_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('SurName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
    ]
