# Generated by Django 5.2.1 on 2026-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstprojectt', '0003_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500)),
                ('Number', models.IntegerField(max_length=10)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
    ]
