# Generated by Django 5.2.1 on 2026-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstprojectt', '0004_contactt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactt',
            name='Number',
            field=models.CharField(max_length=15),
        ),
    ]
