# Generated by Django 5.2.1 on 2026-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstprojectt', '0005_alter_contactt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactt',
            name='Feedback',
            field=models.TextField(blank=True),
        ),
    ]
